Repository apache/incubator-openwhisk-apigateway, pull requests merged in 2018-05, with the labels that each got.

#292 Support ASF Header in .md and .sh files for scancode
  CONTRIBUTING.md
  README.md
  build_config_supervisor.sh
  build_profiling.sh
  doc/v1/management_interface_v1.md
  doc/v1/policies.md
  doc/v1/security.md
  doc/v2/management_interface_v2.md
  init.sh
  tests/install-deps.sh
  tests/run-tests.sh
Labels: apache, review

#296 Ensure donated IBM code uses Apache 2 headers.
  conf.d/managed_endpoints.conf
  conf.d/management_apis.conf
Labels: apache

#293 updated some licenses to ASF and removed naxsi module
  Dockerfile
  api-gateway.conf
  conf.d/api_gateway_init.conf
  conf.d/api_gateway_logging.conf
  conf.d/blacklist.conf
  conf.d/commons/common-headers.conf
  conf.d/default.conf
  conf.d/includes/analytics_endpoints.conf
  conf.d/includes/basic_endpoints.conf
  html/index.html
  tests/test_initialization.t
Labels: apache

#298 Change hash header to latest version in .conf files.
  CONTRIBUTING.md
  DEPENDENCIES.md
  README.md
  api-gateway.conf
  conf.d/api_gateway_init.conf
  conf.d/api_gateway_logging.conf
  conf.d/blacklist.conf
  conf.d/commons/common-headers.conf
  conf.d/default.conf
  conf.d/includes/analytics_endpoints.conf
  conf.d/includes/basic_endpoints.conf
  conf.d/managed_endpoints.conf
  conf.d/management_apis.conf
  doc/profiling.md
  doc/v1/management_interface_v1.md
  doc/v1/policies.md
  doc/v1/security.md
  doc/v2/management_interface_v2.md
  tests/scripts/lua/lib/logger.lua
  tests/scripts/lua/lib/request.lua
  tests/scripts/lua/lib/utils.lua
  tests/set_paths.lua
Labels: apache, review

#301 Add ASF license header to travis yaml file.
  .travis.yml
Labels: apache, license

#303 Fix minor scancode EOL error in index.html.
  html/index.html
Labels: apache

#305 Fix ASF license header in rules config. file.
  naxsi_core.rules
Labels: apache, wip
